### ISSUE TITLE
Result is not as ideal as original paper

### ISSUE THREAD

**Issue by MeLonJ10** [ChengBinJin/Real-time-style-transfer#2]
Thanks a lot for ur implementation. I have re-implemented this paper following ur code. But the result was not as ideal as the original paper. Espeicially, the generater images are kinds of speckled. Did u find such phenomenon?

**Comment by ChengBinJin** [comment]
@MeLonJ10 
Yeah, I agree with you. The real-time style transform method has a training stage. Therefore, the perceptual results are highly depended on the selected checkpoints. For finding an acceptable outcome, a lot of tuning-processes are needed.
